name: Clone and Compress Kiwi Browser

on:
  workflow_dispatch:  # Bisa dijalankan manual dari GitHub Actions

jobs:
  clone-compress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (p7zip)
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: Clone Kiwi Browser source code
        run: |
          git clone --depth=1 https://github.com/kiwibrowser/src.git kiwi_source
      - name: Compress with high compression (7z)
        run: |
          7z a -t7z kiwi_source.7z ./kiwi_source


      - name: Compress with high compression (7z)
        run: |
          7z a -t7z -mx=9 kiwi_hg.7z kiwi_source.7z

      - name: Upload compressed file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: kiwi_source
          path: kiwi_source.7z
          retention-days: 7  # Hapus setelah 7 hari

      - name: Commit and push compressed file to repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          mv kiwi_source.7z .
          git add kiwi_source.7z
          git commit -m "Add compressed Kiwi Browser source"
          git push
