name: Build Kiwi Library (Multi-Arch with Ubuntu 16.04)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: [arm, arm64, x86, x86_64]  # Multi-architecture build
    runs-on: ubuntu-latest  # Gunakan Ubuntu terbaru untuk menjalankan Docker

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run Ubuntu 16.04 in Docker
        run: |
          docker run --rm -v $GITHUB_WORKSPACE:/workspace -w /workspace ubuntu:16.04 bash -c "
            echo 'Mengupdate dan menginstal dependensi...';
            apt update &&
            apt install -y sudo curl git python python-dev build-essential software-properties-common &&
            add-apt-repository ppa:deadsnakes/ppa -y &&
            apt update &&
            apt install -y python3 python3-dev python3-pip libssl-dev libffi-dev libgcc-5-dev &&
            
            echo 'Mengkloning source code Kiwi Browser...';
            git clone --depth 1 https://github.com/kiwibrowser/src.git kiwi &&
            cd kiwi &&

            echo 'Menginstal dependencies Chromium...';
            yes | ./build/install-build-deps.sh &&

            echo 'Menjalankan proses build untuk arsitektur ${{ matrix.arch }}...';
            ARCH=${{ matrix.arch }}
            gn gen out/${ARCH} --args=\"target_os=\\\"android\\\" target_cpu=\\\"${ARCH}\\\" is_debug=false symbol_level=0 is_official_build=true enable_extensions=true proprietary_codecs=true enable_nacl=false\" &&
            ninja -C out/${ARCH} libkiwi.so &&
            
            echo 'Build selesai!'
          "

      - name: Upload Library Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kiwi-libraries-${{ matrix.arch }}
          path: kiwi/out/${{ matrix.arch }}/libkiwi.so
