name: Build Kiwi Library (Multi-Arch)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: [arm, arm64, x86, x86_64]  # Multi-architecture build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 git wget curl clang cmake ninja-build

      - name: Setup Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          export ANDROID_NDK=$GITHUB_WORKSPACE/android-ndk-r25b
          export PATH=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

      - name: Configure & Build Kiwi Library (Multi-Arch)
        run: |
          git clone --depth 1 https://github.com/kiwibrowser/src.git kiwi
          cd kiwi
          yes | ./build/install-build-deps.sh --unsupported  # Mengatasi error distro tidak didukung

          # Tentukan arsitektur
          ARCH=${{ matrix.arch }}

          # Gunakan custom build flags
          gn gen out/${ARCH} --args="target_os=\"android\" target_cpu=\"${ARCH}\" is_debug=false symbol_level=0 is_official_build=true enable_extensions=true proprietary_codecs=true enable_nacl=false"
          ninja -C out/${ARCH} libkiwi.so

      - name: Upload Library Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kiwi-libraries-${{ matrix.arch }}
          path: kiwi/out/${{ matrix.arch }}/libkiwi.so
