name: Build Kiwi Library (Multi-Arch)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: [arm, arm64, x86, x86_64]  # Multi-architecture build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 git wget curl clang cmake ninja-build

      - name: Setup Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          export ANDROID_NDK=$GITHUB_WORKSPACE/android-ndk-r25b
          export PATH=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

      - name: Configure & Build Kiwi Library (Multi-Arch)
        run: |
          git clone --depth 1 https://github.com/kiwibrowser/src.git kiwi
          cd kiwi
      - name: Install Dependencies (Skip Errors)
        run: |
          yes | ./build/install-build-deps.sh --unsupported || true

      - name: Install Missing Packages (Manual Fix)
        run: |
          sudo apt update
          sudo apt install -y \
            libncurses5 \
            libpango-1.0-0 \
            libssl-dev \
            libgcc-s1 \
            libncurses5-dev \
            libapache2-mod-php \
            libappindicator3-dev \
            libasound2 \
            libffi-dev \
            libfontconfig1 \
            libgnome-keyring-dev \
            libgtk-3-dev \
            libnspr4 \
            libnss3 \
            libpixman-1-0 \
            libsqlite3-dev \
            libstdc++6 \
            libxau6 \
            libxcb1 \
            libxcomposite1 \
            libxext6 \
            libxinerama1 \
            php-cli \
            python3 \
            python3-pip \
            python3-crypto \
            python3-dev \
            python3-numpy \
            python3-opencv \
            python3-openssl \
            python3-psutil \
            python3-yaml \
            zlib1g

          # Tentukan arsitektur
          ARCH=${{ matrix.arch }}

          # Gunakan custom build flags
          gn gen out/${ARCH} --args="target_os=\"android\" target_cpu=\"${ARCH}\" is_debug=false symbol_level=0 is_official_build=true enable_extensions=true proprietary_codecs=true enable_nacl=false"
          ninja -C out/${ARCH} libkiwi.so

      - name: Upload Library Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kiwi-libraries-${{ matrix.arch }}
          path: kiwi/out/${{ matrix.arch }}/libkiwi.so
