name: Build Kiwi Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 git wget curl clang cmake ninja-build

      - name: Setup Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          export ANDROID_NDK=$GITHUB_WORKSPACE/android-ndk-r25b
          export PATH=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

      - name: Configure & Build Kiwi Library
        run: |
          git clone --depth 1 https://github.com/kiwibrowser/src.git kiwi
          cd kiwi
          ./build/install-build-deps.sh
          gn gen out/Default --args='target_os="android" target_cpu="arm64" is_debug=false symbol_level=0'
          ninja -C out/Default libkiwi.so

      - name: Upload Library Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kiwi-libraries
          path: kiwi/out/Default/*.so
